language: python
python:
  - "3.3"
  - "3.4"

sudo:
  false

install:

  # Install conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
    # Useful for debugging any issues with conda
  - conda info -a

    # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pip setuptools pillow pyqt
  - source activate test-environment
#  - python setup.py install

#  - sudo pip install conda
#  # install deps
#  - sudo conda init
#  # update conda. The following line throws an error
##  - sudo conda update --yes conda
#  - conda create -p $HOME/py --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pip setuptools pillow pyqt
#  - export PATH=$HOME/py/bin:$PATH

  - pip install pydicom
  - pip install coveralls

  # install your own package into the environment
  - python setup.py install
  # attempt to fix DISPLAY variable errors of matplotlib's. See: https://github.com/mwaskom/seaborn/pull/97
  - cp tests/matplotlibrc .

# test script
script:
  - python setup.py test
#  - coverage run --source=pylinac setup.py test

after_success:
  coveralls

notifications:
  email: false

branches:
  except:
   - minified
